### This script compare tracklet objects produced by generate_tracklets.py and tracklets obtained from DeepEIoU tracker.
### Comparison is mainly about structure of the tracklet objects and filed array dimension.

In [19]:
import numpy as np
import pickle
import os

In [20]:
class Tracklet:
    def __init__(self, track_id, frame, score, bbox, feat=None):
        # frame (float), score (float), bbox (list(4))
        self.track_id = track_id
        self.scores = [score]
        self.times = [frame]
        self.bboxes = [bbox]
        self.features = [] if feat is None else [feat]

    def append_det(self, frame, score, bbox):
        # frame (float), score (float), bbox (list(4))
        self.scores.append(score)
        self.times.append(frame)
        self.bboxes.append(bbox)

    def append_feat(self, feat):
        # feat (numpy array)
        self.features.append(feat)

In [21]:
# Load a tracklet file for a SportsMOT sequence
sports_trklets_path = r"C:\Users\Ciel Sun\OneDrive - UW\EE 599\DeepEIoU\deep-eiou-tmp\Tracklets\v_1UDUODIBSsc_c001.pkl"
with open(sports_trklets_path, 'rb') as pkl_f:
    sports_tid2track = pickle.load(pkl_f)

print(type(sports_tid2track))
for i, (track_id, strack) in enumerate(sports_tid2track.items()):
    print(track_id)
    print(len(strack.times))
    print(len(strack.bboxes))
    print(np.array(strack.features).shape)
    break



<class 'collections.defaultdict'>
1
308
308
(308, 512)


In [23]:
# Load a tracklet file for a SoccerNet sequence
soccer_trklets_path = r"C:\Users\Ciel Sun\OneDrive - UW\EE 599\SoccerNet\tracking-2023\test_Seq_Tracklets\SNMOT-116.pkl"
with open(soccer_trklets_path, 'rb') as pkl_f:
    soccer_tid2track = pickle.load(pkl_f)

print(type(soccer_tid2track))
for i, (track_id, tracklet) in enumerate(soccer_tid2track.items()):
    print(track_id)
    print(len(tracklet.times))
    print(len(tracklet.bboxes))
    print(np.array(tracklet.features).shape)
    break

<class 'dict'>
1.0
176
176
(176, 512)


In [26]:
import numpy as np
import torch

# Example list of numpy arrays
array_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

# Combine the numpy arrays into one array
combined_array = np.stack(array_list)

labels = np.array([0, 1, 1])
print(combined_array[labels == 1])

# Convert the numpy array to a PyTorch tensor
tensor = torch.from_numpy(combined_array)

# Print the tensor
print(tensor)


a = np.array([[4, 5, 6, 6],  [2, 3, 4, 5]])
np.argmin(np.array(a))

[[4 5 6]
 [7 8 9]]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


4

In [27]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Find the index of the maximum value
max_index_flattened = np.argmax(array_2d)  # This returns the index in the flattened array
max_index_2d = np.unravel_index(max_index_flattened, array_2d.shape)  # Convert to a tuple of indices for 2D

print("Index of maximum value:", max_index_2d)
print(np.any(array_2d > 4))

Index of maximum value: (1, 2)
True


In [29]:
a = np.ones((4, 4))
diagonal_mask = np.eye(a.shape[0], dtype=bool)
non_diagonal_mask = ~diagonal_mask
a[non_diagonal_mask]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])