### This script compare tracklet objects produced by generate_tracklets.py and tracklets obtained from DeepEIoU tracker.
### Comparison is mainly about structure of the tracklet objects and filed array dimension.

In [2]:
import numpy as np
import pickle
import os

In [7]:

class Tracklet:
    def __init__(self, track_id=None, frames=None, scores=None, bboxes=None, feats=None):
        '''
        Initialize the Tracklet with IDs, times, scores, bounding boxes, and optional features.
        If parameters are not provided, initializes them to None or empty lists.

        Args:
            track_id (int, optional): Unique identifier for the track. Defaults to None.
            frames (list or int, optional): Frame numbers where the track is present. Can be a list of frames or a single frame. Defaults to None.
            scores (list or float, optional): Detection scores corresponding to frames. Can be a list of scores or a single score. Defaults to None.
            bboxes (list of lists or list, optional): Bounding boxes corresponding to each frame. Each bounding box is a list of 4 elements. Defaults to None.
            feats (list of np.array, optional): Feature vectors corresponding to frames. Each feature should be a numpy array of shape (512,). Defaults to None.
        '''
        self.track_id = track_id
        self.parent_id = None
        self.scores = scores if isinstance(scores, list) else [scores] if scores is not None else []
        self.times = frames if isinstance(frames, list) else [frames] if frames is not None else []
        self.bboxes = bboxes if isinstance(bboxes, list) and bboxes and isinstance(bboxes[0], list) else [bboxes] if bboxes is not None else []
        self.features = feats if feats is not None else []

    def append_det(self, frame, score, bbox):
        '''
        Appends a detection to the tracklet.

        Args:
            frame (int): Frame number for the detection.
            score (float): Detection score.
            bbox (list of float): Bounding box with four elements [x, y, width, height].
        '''
        self.scores.append(score)
        self.times.append(frame)
        self.bboxes.append(bbox)

    def append_feat(self, feat):
        '''
        Appends a feature vector to the tracklet.

        Args:
            feat (np.array): Feature vector of shape (512,).
        '''
        self.features.append(feat)

    def extract(self, start, end):
        '''
        Extracts a subtrack from the tracklet between two indices.

        Args:
            start (int): Start index for the extraction.
            end (int): End index for the extraction.

        Returns:
            Tracklet: A new Tracklet object that is a subset of the original from start to end indices.
        '''
        subtrack = Tracklet(self.track_id, self.times[start:end + 1], self.scores[start:end + 1], self.bboxes[start:end + 1], self.features[start:end + 1] if self.features else None)
        return subtrack


In [ ]:
# Load a tracklet file for a SportsMOT sequence
sports_trklets_path = r"C:\Users\Ciel Sun\OneDrive - UW\EE 599\DeepEIoU\deep-eiou-tmp\Tracklets\v_1UDUODIBSsc_c001.pkl"
with open(sports_trklets_path, 'rb') as pkl_f:
    sports_tid2track = pickle.load(pkl_f)

print(type(sports_tid2track))
for i, (track_id, strack) in enumerate(sports_tid2track.items()):
    print(track_id)
    print(len(strack.times))
    print(len(strack.bboxes))
    print(np.array(strack.features).shape)
    break



In [10]:

soccer_trklets_path = r"C:\Users\Ciel Sun\OneDrive - UW\EE 599\SportsMOT\DeepEIoU_results\DeepEIoU_Tracklets_test\v_1UDUODIBSsc_c001.pkl"
with open(soccer_trklets_path, 'rb') as pkl_f:
    soccer_tid2track = pickle.load(pkl_f)

print(type(soccer_tid2track))
for i, (track_id, tracklet) in enumerate(soccer_tid2track.items()):
    print(track_id)
    print(len(tracklet.times))
    print(len(tracklet.bboxes))
    print(np.array(tracklet.features).shape)
    break

<class 'dict'>
1.0
308
308
(308, 512)


In [26]:
import numpy as np
import torch

# Example list of numpy arrays
array_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

# Combine the numpy arrays into one array
combined_array = np.stack(array_list)

labels = np.array([0, 1, 1])
print(combined_array[labels == 1])

# Convert the numpy array to a PyTorch tensor
tensor = torch.from_numpy(combined_array)

# Print the tensor
print(tensor)


a = np.array([[4, 5, 6, 6],  [2, 3, 4, 5]])
np.argmin(np.array(a))

[[4 5 6]
 [7 8 9]]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


4

In [27]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Find the index of the maximum value
max_index_flattened = np.argmax(array_2d)  # This returns the index in the flattened array
max_index_2d = np.unravel_index(max_index_flattened, array_2d.shape)  # Convert to a tuple of indices for 2D

print("Index of maximum value:", max_index_2d)
print(np.any(array_2d > 4))

Index of maximum value: (1, 2)
True


In [29]:
a = np.ones((4, 4))
diagonal_mask = np.eye(a.shape[0], dtype=bool)
non_diagonal_mask = ~diagonal_mask
a[non_diagonal_mask]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [1]:
seq_tracks_dir = r'C:\Users\Ciel Sun\OneDrive - UW\EE 599\SportsMOT\ByteTrack_results\ByteTrack_Tracklets_test'

print('SportsMOT' in seq_tracks_dir)

True
